# Generated by Django 2.0.5 on 2018-06-19 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IdcManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': 'IDC服务器', 'verbose_name_plural': 'IDC服务器'},
        ),
        migrations.AddField(
            model_name='idc',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(max_length=128, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='录入时间'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='desc',
            field=models.CharField(max_length=128, verbose_name='服务器描述'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=64, verbose_name='服务器名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='联系电话'),
        ),
    ]
